### PR TITLE
fno-stack-protector: Disable stack protector

### PR DESCRIPTION
**Pull request by ipochi**
This commit adds the `f-no-stack-protector` as an extra Clang flags as
on some distributions the toolchain might have stack protector enabled
by default.

Case in point Archlinux Kernel 5.9.9

Signed-off-by: Imran Pochi <imran@kinvolk.io>

### CODE REVIEW

**Review by alban — COMMENTED** [review]
Did you commit a file `pkg/filters/tc-bpf/-fno-stack-protector` by mistake?

**Comment by ipochi** [comment]
> Did you commit a file `pkg/filters/tc-bpf/-fno-stack-protector` by mistake?

no @alban Once I compiled the code again `make`. This file got generated.

**Comment by alban** [comment]
It looks like the compiler was called with `clang -E -o $(EXTRA_CFLAGS)` by mistake in a previous version?

**Comment by ipochi** [comment]
> It looks like the compiler was called with `clang -E -o $(EXTRA_CFLAGS)` by mistake in a previous version?

It seems you are right , I deleted the file and compiled again. This file wasn't generated. I assumed otherwise.

**Comment by ipochi** [comment]
@alban 

Updated the PR.

**Review by alban — APPROVED** [review]
LGTM

Out of curiosity, what is the version of your `go-bindata`?

Mine is:
```
$ go-bindata --version
go-bindata 3.1.0 (Go runtime go1.14beta1).
Copyright (c) 2010-2013, Jim Teeuwen.
```

I guess we might not have the same version because `pkg/filters/tc-bpf/bpf-assets.go` is formatted differently in your PR.

**Comment by ipochi** [comment]
> LGTM
> 
> Out of curiosity, what is the version of your `go-bindata`?
> 
> Mine is:
> 
> ```
> $ go-bindata --version
> go-bindata 3.1.0 (Go runtime go1.14beta1).
> Copyright (c) 2010-2013, Jim Teeuwen.
> ```
> 
> I guess we might not have the same version because `pkg/filters/tc-bpf/bpf-assets.go` is formatted differently in your PR.

@alban 
```
go-bindata --version
go-bindata 3.5.2 (Go runtime go1.14.4).
Copyright (c) 2010-2015, Jim Teeuwen.
Copyright (c) 2016-2020, go-bindata Authors.
```

**Pull request merged**
